language: objective-c
osx_image: xcode7.1
script:
    - set -o pipefail
    - xcodebuild -project QueryKit.xcodeproj -scheme QueryKit test -sdk macosx | xcpretty -c
    - xcodebuild -project QueryKit.xcodeproj -scheme QueryKit test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
    - pod lib lint --allow-warnings --quick
